### ISSUE TITLE
icon cutting & bad rotation

### ISSUE THREAD

**Issue by zhouzzu2008** [ufna/VaTexAtlas#21]
I generated a atlas texture which contains prop icons and button icons with different rotations.  Once I import .vta file to Unreal Engine, In frame folder some prop icons have wrong rotation and some button icons(rotated) are cutted. If Use the same settings with TexturePacker, and import as paper2dsprints, all the icons are fine.

**Comment by ufna** [comment]
Hi @zhouzzu2008 ,

Icon rotation is not supported by VTA plugin. Unfortunately I have no plans to support it.
