### ISSUE TITLE
Tiling and Border mode not working for atlas textures

### ISSUE THREAD

**Issue by MarcoTansini** [ufna/VaTexAtlas#24]
Hello, I'm using a UImage to display a VTASlateTexture:
If i select any tiling option other than none when drawing as "Image", or if i select the "Border" draw mode, the image displays the neighbouring textures in the atlas instead of working as it should.

Any plan to fix this?
Thanks

**Comment by ufna** [comment]
Hi @MarcoTansini ,

VaTexAtlas is definitely not supported anymore, I recommend to use atlases from Paper2D plugin.
